### ISSUE TITLE
Automate the management of public devices list

### ISSUE THREAD

**Issue by cbjuan** [Qiskit/qiskit-code-assistant-vscode#35]
### What is the expected enhancement?
As suggested by @jaygambetta in https://github.com/Qiskit/qiskit-vscode/pull/34#issuecomment-424795678, we must automate the management of the public devices list to avoid errors and bad behaviors when the list changes (release of new devices, etc.). 

Related to #34

**Comment by AkashGutha** [comment]
@cbjuan I've been looking into this. But I'm unable to figure out the API. Is there a place where I can find more information about the Backend API or is it not for public use?

**Comment by cbjuan** [comment]
Hi Akash 

For now, we don't have access to a public API that provides this kind of info. We are talking with other colleagues at IBM to expose this info. 

Currently, this issue is more a "reminder" rather than a real problem to solve at this moment.

**Comment by cbjuan** [comment]
The extension has changed substantially with after the 1st commit in years (and the un-archive of the repo) https://github.com/Qiskit/qiskit-code-assistant-vscode/commit/7a248ac7f8502ee527f442c33cdb1697e00297c4

This issue is not relevant anymore, closing. Thanks
