### ISSUE TITLE
Interaction between Pylint and Qiskit extension

### ISSUE THREAD

**Issue by ydarias** [Qiskit/qiskit-code-assistant-vscode#54]
### Informations

-   **VSCode version**:
-   **Qiskit [Terra / Aqua / other] version**:
-   **Qiskit VSCode Extension version**:
-   **Operating system**:

### What is the current behavior?

Pylint is signaling some errors that are no real errors.

```
{
    "resource": "/Users/ccp/Development/ibmq/qiskit/oracle/indexTalk2.py",
    "owner": "python",
    "code": "E1101",
    "severity": 8,
    "message": "E1101:Instance of 'QuantumCircuit' has no 'cx' member",
    "source": "pylint",
    "startLineNumber": 31,
    "startColumn": 9,
    "endLineNumber": 31,
    "endColumn": 9
}
```

As reported by `@ccpalmer` at Slack.

**Comment by ccpalmer** [comment]
Status says needs more information: what do you need?

**Comment by ccpalmer** [comment]
VSCode version:  **1.30**
Qiskit [Terra / Aqua / other] version: **0.6.1**
Qiskit VSCode Extension version: **0.4.1**
Operating system: **OSX 10.14.2**

**Comment by cbjuan** [comment]
We need to replicate the error to understand what is happening and later fix it. That is the info. But thanks for your reply, @ccpalmer

**Comment by MatthewGregoire42** [comment]
I am having a similar problem. Here is a screenshot of an example:

![image](https://user-images.githubusercontent.com/42555641/57964041-3652d280-78fc-11e9-8bd3-8ef81d87f539.png)

It seems that for every gate applied to a circuit, pylint gives the error `Instance of 'QuantumCircuit' has no 'gate' member pylint(no-member)`. This doesn't affect how the code runs, but the numerous red underlines are annoying.

VS Code version: **1.33.1**
Qiskit version: **0.10.1**
VS Code Qiskit extension version: **0.5.4**
Python version: **3.6.8**
OS: **Windows 10**

To replicate, use the software above, and the Python extension (version 2019.4.1254), and apply gates to a circuit as shown in the screenshot above.

**Comment by cbjuan** [comment]
The extension has changed substantially with after the 1st commit in years (and the un-archive of the repo) https://github.com/Qiskit/qiskit-code-assistant-vscode/commit/7a248ac7f8502ee527f442c33cdb1697e00297c4

This issue is not relevant anymore, closing. Thanks
