### ISSUE TITLE
Problems with white spaces in the path name of the file

### ISSUE THREAD

**Issue by ydarias** [Qiskit/qiskit-code-assistant-vscode#55]
### Informations

-   **VSCode version**:
-   **Qiskit [Terra / Aqua / other] version**:
-   **Qiskit VSCode Extension version**:
-   **Operating system**:

### What is the current behavior?

Original message from Craig Spiteri at the Slack channel

```
... Don't have a <space> in the path name to the file. In hindsight the message does say it couldn't find the file ...
```

**Comment by AkashGutha** [comment]
@ydarias Can you provide more information on this. I'd like to take a look at this.

**Comment by ydarias** [comment]
Yeah @AkashGutha, we didn't replicate the error yet, but it is related with having spaces in the path to the file that is being edited. For example, if you have a file called `/home/yeray/myfile.py` it works, but if you have `/home/yeray/my folder/myfile.py` it doesn't. 

But lets ask @cbjuan if he remember something more about it :-)

**Comment by cbjuan** [comment]
Yes, it seems to be a problem related to having white spaces in the path. We don't have much more info. For now, we should add a python method to check/transform the path.

**Comment by cbjuan** [comment]
The extension has changed substantially with after the 1st commit in years (and the un-archive of the repo) https://github.com/Qiskit/qiskit-code-assistant-vscode/commit/7a248ac7f8502ee527f442c33cdb1697e00297c4

This issue is not relevant anymore, closing. Thanks
