### ISSUE TITLE
IBMQ Devices Status error

### ISSUE THREAD

**Issue by MatthewGregoire42** [Qiskit/qiskit-code-assistant-vscode#87]
### Informations

-   **VSCode version**: 1.33.1
-   **Qiskit [Terra] version**: 0.8.0
-   **Qiskit VSCode Extension version**: 0.5.4
-   **Operating system**: Windows 10

### What is the current behavior?

Clicking on the button "IBMQ Devices Status" results in the following error message:

`"c:\Users\matth\.vscode\extensions\qiskit.qiskit-vscode-0.5.4\resources\qiskitScripts\listRemoteBackends.py", line 16, in <module> from qiskitTools import QiskitTools File "c:\Users\matth\.vscode\extensions\qiskit.qiskit-vscode-0.5.4\resources\qiskitScripts\qiskitTools.py", line 13, in <module> from qiskit.wrapper import load_qasm_file ModuleNotFoundError: No module named 'qiskit.wrapper'`

I assume this has to do with compatibility with Terra 0.8.0?

### Steps to reproduce the problem

Use Python 2.6.8 and the software versions above.

### What is the expected behavior?

The button should work 😄

**Comment by cbjuan** [comment]
Hi @MatthewGregoire42! Thanks for your issue. We'll solve it as soon as possible.

Kind regards

**Comment by tobeyOguney** [comment]
I am also facing the described challenge. However, my "Informations" are:

* VSCode version: 1.33.1
* Python version: 3.6.7
* Qiskit [Terra] version: 0.8.2
* Qiskit VSCode Extension version: 0.5.5
* Operating system: Ubuntu 18.04.2 LTS

**Comment by cbjuan** [comment]
The extension has changed substantially with after the 1st commit in years (and the un-archive of the repo) https://github.com/Qiskit/qiskit-code-assistant-vscode/commit/7a248ac7f8502ee527f442c33cdb1697e00297c4

This issue is not relevant anymore, closing. Thanks
