### ISSUE TITLE
Travis deployment with Linux fails

### ISSUE THREAD

**Issue by ydarias** [Qiskit/qiskit-code-assistant-vscode#9]
### Informations

- **VSCode version**: 1.25.1
- **Qiskit (Python SDK) version**: 0.5.3
- **Qiskit VSCode Extension version**: 0.2.3
- **Operating system**: Travis with Linux

### What is the current behavior?

The deployment task is failing when it is launched by Travis.

### Steps to reproduce the problem

Just execute the build at Travis using the valid branch and tag.

### What is the expected behavior?

Travis should build, test and deploy automatically without any incidents.

### Suggested solutions

The problem is related with the `fsevents` dependency because it is only valid for `osx`. This dependency is required by Nunjucks, so there are only two options available:
1. Modifying `vsce` command to not check the dependencies of an extension, if that is possible at all.
2. Replacing Nunjucks with another template engine.

**Comment by cbjuan** [comment]
The extension has changed substantially with after the 1st commit in years (and the un-archive of the repo) https://github.com/Qiskit/qiskit-code-assistant-vscode/commit/7a248ac7f8502ee527f442c33cdb1697e00297c4

This issue is not relevant anymore, closing. Thanks
