### ISSUE TITLE
The QAsm Language support server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by ghost** [Qiskit/qiskit-code-assistant-vscode#90]
### Informations

-   **VSCode version**: 1.38.1
-   **Qiskit [Terra / Aqua / Ignis/Aer] version**: 0.9.0/0.6.0/0.2.0/0.3.0
-   **Qiskit Version**:0.12.0
-   **Qiskit VSCode Extension version**:0.5.5
-   **Operating system**: Windows 10 Home 1903 Build 18362.356
-   **Python Environment /Version**:Anaconda/ 3.7.3

### What is the current behavior?
The extension is not working at all.
### Steps to reproduce the problem
After VS Code is launched and any qasm file is opened the notification occurs saying "The QAsm Language support server crashed 5 times in the last 3 minutes. The server will not be started."
![image](https://user-images.githubusercontent.com/42297946/64905014-c7da2180-d6ef-11e9-9724-f113e04daeae.png)

**Comment by cbjuan** [comment]
The extension has changed substantially with after the 1st commit in years (and the un-archive of the repo) https://github.com/Qiskit/qiskit-code-assistant-vscode/commit/7a248ac7f8502ee527f442c33cdb1697e00297c4

This issue is not relevant anymore, closing. Thanks
